### ISSUE TITLE
iphone_rusher.rb:121:in `select_store': undefined method `click' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tian4546** [pulltheflower/iphone-rusher#2]
iphone_rusher.rb:121:in `select_store': undefined method `click' for nil:NilClass (NoMethodError)
        from iphone_rusher.rb:100:in `refresh_until'
        from iphone_rusher.rb:18:in `rush'
        from iphone_rusher.rb:140:in `<main>'

**Comment by tian4546** [comment]
![image](https://user-images.githubusercontent.com/14542275/138445691-f8f87663-8785-4b7c-9eac-4e21401d1196.png)
driver.find_elements(css: '.as-storelocator-searchresultlist .as-storelocator-searchitem').first.click  这2个样式class 搜索这个页面没有

**Comment by pulltheflower** [comment]
这个问题应该是有时候商店列表刷新之后没有显示出来，已经加上了判断，只有在有这个元素的时候才停止刷新

**Comment by pulltheflower** [comment]
https://github.com/pulltheflower/iphone-rusher/commit/3aa4eaa70ded9036199c7049110d9a9afda118fa
